package excaptionHandlingPackage;

public class exceptionHandlingExample3 {
	public static void main(String[] args) {

		try {
			int a[] = new int[12];
			a[14] = 45 / 0;
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("XX " + "Out Of Bound" + " XX");
		} catch (ArithmeticException e) {
			System.out.println("++ " + "Arithmetic Exception" + " ++");
		} catch (Exception e) {
			System.out.println("+X " + "Exception Detected" + " X+");
		}
		System.out.println("Continue...");

	}

}
